### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by XVincentX** [launchdarkly/.net-client#1]
Hello,
I was having a look into your .net client and I have some "objection/fixes" that can definitely improve the library.

I saw from your README that everything is still in alpha, so I preferred to ask (perhaps you are going to replace all this stuff today :smile: ) 
Would you be available to discuss/accept a pull request for that?

**Comment by jkodumal** [comment]
Hi @XVincentX, 

We'd be happy to discuss changes, and of course we'll take pull requests!

best,
John

**Comment by XVincentX** [comment]
Great. I will try to arrange something as soon as possible and open a PR for that.

**Comment by jkodumal** [comment]
PR merged. Thanks!
