### ISSUE TITLE
Allow app name identification in event log

### ISSUE THREAD

**Issue by gzak** [launchdarkly/.net-client#17]
In addition to knowing which user was requesting which feature, it would be nice to know which app the request was coming from.

One way would be to allow developers to pass in an app name string as part of the `LdClient` constructor (like one of the things you can configure).

**Comment by arun251** [comment]
Hi @gzak , is this request regarding the events in the Dev Console? If so, when you click an event there, you can see the full details of the `LDUser` object (including custom attributes). If you pass the app name as a custom attribute, you can see the detail in the Dev Console. Does that work for you?

**Comment by gzak** [comment]
It does, but it's not very maintainable - now callers have to remember to pass in the application name everywhere they use it, rather than just configuring it once in the application startup and just injecting the client.

**Comment by gzak** [comment]
Also, forgot to mention: in addition to the dev console, it could be useful in analytics, so we know which system the user interacted with at the time they got a treatment (in the case of a toggle shared by multiple applications).

**Comment by arun251** [comment]
Thanks for the details, @gzak . I added this to our internal backlog. We encourage you to send these feature requests to support@launchdarkly.com. This request is not specific to the .NET SDK and would require some service changes, so I'm going to close this issue here.
