### ISSUE TITLE
Implement SSE-based streaming with SignalR

### ISSUE THREAD

**Issue by jkodumal** [launchdarkly/.net-client#19]
SignalR appears to be a well-tested SSE client library. Implement streaming using SignalR and make it the default behavior.

**Comment by jkodumal** [comment]
This would make #18 far less critical.

**Comment by drichelson** [comment]
Unfortunately, it looks like SignalR is not a general-purpose SSE client: https://forums.asp.net/t/1981411.aspx?problem+receiving+SSE+s+from+a+non+Microsoft+web+site
