### ISSUE TITLE
version >= 3 dependency bloat

### ISSUE THREAD

**Issue by richrout** [launchdarkly/.net-client#39]
We're running a .net framework MVC application (not .net core). When I nuget install the client (any version 3 and up), I end up with a whole bunch of .net core dependencies being added to my project (System.IO, System.Threading, etc). I'm sure they're not doing much harm, but now my packages folder is huge, it's basically re-downloading the .net framework.

There should be a way of targeting .net core vs .net framework  for the nuget dependencies. Or is there another way around this?

Cheers

**Comment by ISkomorokh** [comment]
+1

**Comment by arun251** [comment]
@richrout This might be fixed as of 3.3.2. Do you still see this issue after updating?

**Comment by richrout** [comment]
@arun251 I'm actually not working on a project that uses this any more. But from a quick peek at the dependencies in nuget it looks like everything was being brought it though the NETStandard.Library package. That reference is now gone for NET Framework, which is good.

Without actually verifying myself, I'd consider this fixed :)

Thanks.
