### ISSUE TITLE
Allow custom storage of features

### ISSUE THREAD

**Issue by ahofman** [launchdarkly/.net-client#45]
In my scenario we are integrating LaunchDarkly with a set of backend services hosted on Azure Service Fabric. The following (admittedly contrived!) scenario is possible:

* Service receives flag value, stores it in-memory
* LaunchDarkly CDN goes down
* Service continues to evaluate the last received value - all good so far
* Service Fabric moves the service partition to another node - losing the in-memory flags
* Service reverts back to default feature flag values and potentially behaves very differently

Service Fabric may move service partitions around the cluster whenever it wants, and there's no way for us to control this. 

The solution would be for us to store the feature flag values in Service Fabric Reliable Dictionaries that are part of the service - this way, when the service partition moves around the cluster, the data moves with it. 

I understand there is support for a shared Redis cache - I don't want to go through the hassle of setting up and maintaining additional moving parts in my deployment if I can get away with it.

Ideally there would be some kind of hook point that would allow us to provide our own implementation for feature storage, that would allow us to store them in a Service Fabric Reliable Dictionary. Adding a generic hook point would allow for any custom implementation. It could be a s simple as allowing clients to provide their own implementation of IFeatureStore? Something similar to what is proposed in #38 but not as complex.

**Comment by shailensukul** [comment]
Something like this from the JavaScript client SDK will also be sufficient:

> Listening to flag change events
> The client uses an event emitter pattern to allow you to subscribe to feature flag changes in real time. To subscribe to all feature flag changes, listen for the change event:
>     client.on('change', function(settings) {
>       console.log('flags changed:', settings); --> Save flags to persistent storage in Service Fabric
>     });

**Comment by drichelson** [comment]
@ahofman Thanks for reaching out. Adding your own implementation of IFeatureStore is a good idea and pretty easy to do. I've added it to our work queue.

**Comment by drichelson** [comment]
@ahofman We just released version 3.2.0 which includes the ability to specify a custom IFeatureStore implementation. Please let us know how it goes!
