### ISSUE TITLE
.NET Standard 1.6 is not supported in UWP apps

### ISSUE THREAD

**Issue by nolanblew** [launchdarkly/.net-client#52]
I cannot add the launch darkly client in a UWP app we've created as UWP only supports .net standard 1.4. Can we add a release in the nuget package for a UWP library or downgrade to .NET Standard 1.4 for those of us on UWP?

.NET Standard version matrix can be found here: https://github.com/dotnet/standard/blob/master/docs/versions.md

**Comment by MMalikKhan** [comment]
@nolanblew i am also looking to add launch darkly to a UWP app, did you happen to resolve this issue or workaround. Our app still support V: 1511 Build: 10586

**Comment by atrakh** [comment]
Hi @nolanblew and @MMalikKhan,

Thank you for bringing this issue to our attention. We've just released LaunchDarkly.Client v3.4.1-beta2, which adds a framework target for netstandard1.4: https://github.com/launchdarkly/.net-client/releases/tag/3.4.1-preview. So, the client should now support older UWP applications. Please try upgrading your clients to the latest pre-release version and let me know if it you run into any issues.
