### ISSUE TITLE
LD .net client BoolVariation method intermittently returning wrong values 

### ISSUE THREAD

**Issue by aloysiustany** [launchdarkly/.net-client#74]
**Scenario:**
We have many specflow tests with BeforeScenario methods. In this BeforeScenario method, we check for a boolean LD flag to decide if we got to ignore that test or continue. 
The specrun executes the tests in 10 threads in parallel. 

**Problem:**
We are seeing that intermittently the BoolVariation check for the flag returns FALSE instead of TRUE. The targeting is ON for this flag in LD and it is configured serve TRUE for all users. 
We reuse the same LD client in a test thread. We noticed that, if the BoolVariation returns FALSE once, it will continue to return FALSE for that flag for all subsequent calls for that flag in that thread.

Is this because LD was not reachable at that time ? How can we know if the client is not able to reach LD for flag value ? What else could possibly be the cause of this issue ?

We even monitored the Dev Console in LD. We see multiple calls for that flag and all returning TRUE. But we do not have any correlation method to check if the BoolVariation method calls that incorrectly returned FALSE did infact reach LD server.

**Comment by sarahlessner** [comment]
Hi Aloysius!

Thanks for reaching out. I see that you also submitted a ticket through our official support desk and I will be following up with you via that ticket today.

If it turns out that there is an issue with the SDK I will escalate to the SDK engineer and we'll be sure to follow up on the issue's resolution here so that other users are aware. 

Best,
Sarah

**Comment by sarahlessner** [comment]
An update on the resolution for future reference:

Running 10 tests in parallel could possibly result in one of the SDKs failing to connect. The SDK has a reconnect strategy to handle any error or failure state that it might encounter. Depending on how quickly these tests occur, it's possible that the tests complete before the SDK is able to reconnect. When implemented as a singleton in a long lived environment it would be unlikely to observe this type of issue occurring. 

Aloysius updated us with the following details of his workaround:

1.       Add a jitter delay in front of every LD client initialize in different threads. This should reduce the burst of network load to LD server during thread initializing.

2.     Added a check to see if the LD client is initialized before calling BoolVariation method. If not initialized, then reinitialize the LD client.
