### ISSUE TITLE
Random Not Thread Safe

### ISSUE THREAD

**Issue by JeffAshton** [launchdarkly/.net-client#75]
@eli-darkly ,  You recently added event sampling, however, you used Random in a context which I believe would be accessed concurrently by multiple threads:

https://github.com/launchdarkly/.net-client/blob/8ed370ab9abc66a1943b60734feaf2ba1dd1d073/src/LaunchDarkly.Client/EventProcessor.cs#L44

Random is not guaranteed to be thread safe

https://msdn.microsoft.com/en-us/library/system.random(v=vs.110).aspx#ThreadSafety

https://stackoverflow.com/questions/3049467/is-c-sharp-random-number-generator-thread-safe

**Comment by eli-darkly** [comment]
Uh-oh, that's certainly true. Fixing this - thanks.

**Comment by eli-darkly** [comment]
Released the fix in version 4.1.1.
