### ISSUE TITLE
Break dependency on ASP.NET

### ISSUE THREAD

**Issue by gzak** [launchdarkly/.net-client#8]
There are other kinds of apps besides webapps, and breaking the dependency on ASP.NET would make LaunchDarkly usable in more applications types (Xamarin game apps come to mind).

**Comment by drichelson** [comment]
Great idea! We can remove the dependency. We'll update this issue when there is more news.

**Comment by ISkomorokh** [comment]
@drichelson Excuse me, but why those lines are a problem (dependent on ASP.NET)?

**Comment by ISkomorokh** [comment]
http://stackoverflow.com/questions/34599802/xamarin-cannot-add-microsoft-aspnet-webapi-client-reference
