### ISSUE TITLE
Upgrade to .NET Core

### ISSUE THREAD

**Issue by gzak** [launchdarkly/.net-client#9]
As of .NET Core 1.0 RC2, packages (like LaunchDarkly) can target multiple framework versions in a single package, going back as far as .NET 4.5.0 and going up to the current .NET Core which is platform independent (no longer bound to Windows!). It would broaden the market for LaunchDarkly, so it would be great to see this upgrade.

**Comment by rip327** [comment]
.Net Core would be great to support native Windows 10 Universal Apps.

**Comment by drichelson** [comment]
I took a brief look at what it would take to build the SDK for .NET Core and one of the biggest hurdles is our logging library: https://github.com/damianh/LibLog
If we moved away from LibLog, we'd need to find a suitable logging facade (something like the equivalent of SLF4J) to ensure maximum compatibility.

**Comment by rip327** [comment]
Thank you for feedback. Windows Event tracing is available to .NetCore and is fast and flexible. But I would like to say support for .NetCore not only for cross platform, but Universal App support (the direction Microsoft is pushing).

**Comment by jkodumal** [comment]
Perhaps Microsoft.Exten­sions.Logging is a closer fit than Windows Event Tracing for this use case?

**Comment by gzak** [comment]
Agreed with @jkodumal, plus Microsoft is trying to pare down on Windows-specific functionality as they try to embrace a more cross-platform paradigm.

Also, if SLF4J is anything like log4j, then there's a very close cousin: log4net. Seems really robust, more so than most logging frameworks I've seen for .NET. Worth a look.

**Comment by drichelson** [comment]
This may be useful: http://www.michael-whelan.net/porting-dotnet-framework-library-to-dotnet-core/

**Comment by DanielSchaffer** [comment]
@drichelson I took a quick pass at porting this to .NET Core: https://github.com/DanielSchaffer/.net-client/commit/374d40d4eaa5c1f5aec1276917267aedad216ccc

Basically:

- The tests pass
- Logging is probably broken - at a minimum, may not be as useful since .NET Core has no StackTrace API
- In that particular commit, the conditional build stuff is disabled in LibLog, because it was broken in VS Code and I just wanted to get something working
- I couldn't figure out a .NET Core equivalent of CachePolicy for HttpClientHandler (WebRequestHandler), so I'm not sure if the etag caching works the same way (TBH, I haven't gotten familiar with that)
- It works! I can get toggles, and updates from the dashboard are reflected in the app. Awesome!

**Comment by jkodumal** [comment]
Legendary! We'll take a look.

**Comment by drichelson** [comment]
@DanielSchaffer thanks for the great start in porting to .NET core! In finishing this work I'm having a hard time finding a .NET core http client with ETag caching support.. CacheCow and others don't support .NET core. Any ideas?

**Comment by drichelson** [comment]
This looks like it might be useful: http://stackoverflow.com/questions/38228197/a-common-class-library-consumed-by-both-net-core-and-net-4-5-2

**Comment by DanielSchaffer** [comment]
@drichelson Unfortunately, I'm not aware of any. I haven't had too much of a need for HTTP clients in my .NET Core adventures so far, and when I have, I've only been using the built in one. [ServiceStack](https://github.com/ServiceStack/ServiceStack) may have one in their stuff, but depending on how selective you can be, that might be a bit of a heavy dependency for what you need.

**Comment by drichelson** [comment]
@DanielSchaffer we just posted a PR for the remainder of .NET core changes, including basic etag caching: #29

**Comment by DanielSchaffer** [comment]
Awesome! Thanks!

**Comment by drichelson** [comment]
@DanielSchaffer @rip327 @gzak @kylelaverty and anyone else: If you're interested in trying out the beta .NET core client, please let me know and I'll send you the .nupkg file.

**Comment by drichelson** [comment]
3.0.0 has been released with .NET core support.
